services:
  backend:
    build: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      STORAGE_PATH: /data/uploads
      MAX_UPLOAD_SIZE_MB: ${MAX_UPLOAD_SIZE_MB:-10}
      TELEGRAM_ALLOWED_USER_IDS: ${TELEGRAM_ALLOWED_USER_IDS:-}
    volumes:
      - storage:/data/uploads
      - ./backend/alembic:/app/alembic  # <-- ДОБАВЬТЕ ЭТУ СТРОКУ
      - ./backend/app:/app/app  
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  storage:
